### ISSUE TITLE
Local imports crash with AWS SDK error when importing from local filesystem

### ISSUE THREAD

**Issue by CloudNiner** [azavea/franklin#480]
**Describe the bug**

```
docker-compose up -d
bloop run application -- import-catalog --catalog-root ~/src/stacframes/examples/aviris/catalog/catalog.jso
n --db-host localhost --db-password franklin --db-name franklin
```

Throws:
```
[E] Exception in thread "main" java.lang.ExceptionInInitializerError                                                                      
[E]     at com.azavea.franklin.crawler.CatalogStacImport.readCollection(CatalogStacImport.scala:60)                                       
[E]     at com.azavea.franklin.crawler.CatalogStacImport.readRoot(CatalogStacImport.scala:73)                                             
[E]     at com.azavea.franklin.crawler.CatalogStacImport.runIO(CatalogStacImport.scala:255)                                               
[E]     at com.azavea.franklin.api.commands.Commands$.runCatalogImport(Commands.scala:94)                                                 
[E]     at com.azavea.franklin.api.Server$.$anonfun$run$1(Server.scala:140)                                                               
[E]     at scala.util.Either.map(Either.scala:353)                                                                                        
[E]     at com.azavea.franklin.api.Server$.run(Server.scala:130)                                                                          
[E]     at cats.effect.IOApp.$anonfun$main$3(IOApp.scala:68)                                                                              
[E]     at cats.effect.internals.IOAppPlatform$.mainFiber(IOAppPlatform.scala:40)                                                         
[E]     at cats.effect.internals.IOAppPlatform$.main(IOAppPlatform.scala:25)                                                              
[E]     at cats.effect.IOApp.main(IOApp.scala:68)                                                                                         
[E]     at cats.effect.IOApp.main$(IOApp.scala:67)                                                                                        
[E]     at com.azavea.franklin.api.Server$.main(Server.scala:34)                                                                          
[E]     at com.azavea.franklin.api.Server.main(Server.scala)                                                                              
[E] Caused by: com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in
 the builder or setup environment to supply a region.
```

If I set `AWS_REGION` in my shell, e.g. `export AWS_REGION=us-east-1` then rerun the import command, imports proceed normally.

**Expected behavior**

Even if my AWS environment isn't quite configured correctly (no default region set via `~/.aws/config`), I wouldn't expect the AWS SDK to be loaded and my credentials read when not performing an import from AWS services.

Local imports should run successfully without loading the AWS SDK.

**Comment by jisantuc** [comment]
I think that's a runtime error, so it's possible this is as simple as making the s3 client lazy -- https://github.com/azavea/franklin/blob/master/application/src/main/scala/com/azavea/franklin/crawler/StacIO.scala#L40-L43
