### ISSUE TITLE
IOException: Too many open files when importing catalog via HTTPS

### ISSUE THREAD

**Issue by CloudNiner** [azavea/franklin#482]
**Describe the bug**

I attempted to run the following import on my local franklin instance:
```
bloop run application -- import-catalog \
  --catalog-root https://aviris-data.s3.amazonaws.com/stac-catalog/catalog.json \
  --db-host localhost --db-password franklin --db-name franklin
```

The imported catalog is public and can be used for testing this error. It contains ~4000 items across 150 collections.

Which failed with the following error:
```
java.lang.IllegalStateException: failed to create a child event loop
Caused by: io.netty.channel.ChannelException: failed to open a new selector
Caused by: java.io.IOException: Too many open files
```

Full stack trace [here](https://github.com/azavea/franklin/issues/482#issuecomment-731197580)

**Expected behavior**

Import completes successfully with no errors.

**Additional context**

I was able to reproduce this both locally and on a deployed Franklin instance in AWS when using the above catalog.

I did not encounter the same error when loading the same catalog from my local filesystem, that imported successfully.

**Comment by CloudNiner** [comment]
Full stack trace:
```
java.lang.IllegalStateException: failed to create a child event loop
--
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:86)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:81)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:68)
at org.asynchttpclient.netty.channel.NioTransportFactory.newEventLoopGroup(NioTransportFactory.java:32)
at org.asynchttpclient.netty.channel.NioTransportFactory.newEventLoopGroup(NioTransportFactory.java:21)
at org.asynchttpclient.netty.channel.ChannelManager.<init>(ChannelManager.java:133)
at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:92)
at sttp.client.asynchttpclient.AsyncHttpClientBackend$.defaultClient(AsyncHttpClientBackend.scala:380)
at sttp.client.asynchttpclient.cats.AsyncHttpClientCatsBackend$.$anonfun$apply$1(AsyncHttpClientCatsBackend.scala:71)
at flatMap @ com.azavea.franklin.crawler.StacIO$.readJsonFromHttp(StacIO.scala:88)
at map @ com.azavea.franklin.crawler.CatalogStacImport.$anonfun$insertItemsForAbsHref$2(CatalogStacImport.scala:220)
at flatMap @ com.azavea.franklin.crawler.StacIO$.readJsonFromHttp(StacIO.scala:88)
at flatMap @ com.azavea.franklin.crawler.CatalogStacImport.readCollection(CatalogStacImport.scala:60)
at map @ com.azavea.franklin.crawler.CatalogStacImport.insertItemsForAbsHref(CatalogStacImport.scala:216)
at flatMap @ com.azavea.franklin.crawler.CatalogStacImport.insertItemsForAbsHref(CatalogStacImport.scala:220)
at void @ com.azavea.franklin.crawler.CatalogStacImport.insertItemsForAbsHref(CatalogStacImport.scala:220)
at blockOn$extension @ doobie.util.transactor$Transactor$fromDriverManager$.$anonfun$create$1(transactor.scala:344)
at $anonfun$tailRecM$1 @ doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$bracketCase$28(kleisliinterpreter.scala:753)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175)
at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:142)
at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:146)
at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37)
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:86)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:81)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:68)
at org.asynchttpclient.netty.channel.NioTransportFactory.newEventLoopGroup(NioTransportFactory.java:32)
at org.asynchttpclient.netty.channel.NioTransportFactory.newEventLoopGroup(NioTransportFactory.java:21)
at org.asynchttpclient.netty.channel.ChannelManager.<init>(ChannelManager.java:133)
at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:92)
at sttp.client.asynchttpclient.AsyncHttpClientBackend$.defaultClient(AsyncHttpClientBackend.scala:380)
at sttp.client.asynchttpclient.cats.AsyncHttpClientCatsBackend$.$anonfun$apply$1(AsyncHttpClientCatsBackend.scala:71)
at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:103)
at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:455)
at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:466)
at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:474)
at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:414)
at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:177)
at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:455)
at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:476)
at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:414)
at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Too many open files
at sun.nio.ch.IOUtil.makePipe(Native Method)
at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:65)
at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:173)
... 38 more
```

**Comment by jisantuc** [comment]
Uhhhh this one's my bad, I put the SttpBackend construction inside the `readJsonFromHttp` method so we're creating all the http resources every time we request something. Blame un-reviewed code during a STAC sprint, sorry! One sec...
